// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoKhh4olbC8chuTHjYRKDk7VCxvMaJw78',
    appId: '1:393426116947:web:6ec799008d5659c3da01a6',
    messagingSenderId: '393426116947',
    projectId: 'pbl-mad',
    authDomain: 'pbl-mad.firebaseapp.com',
    storageBucket: 'pbl-mad.firebasestorage.app',
    measurementId: 'G-LBGL6Z9MZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlGKV3wBeTRG3rUwz530SNhWk6dQUJBU',
    appId: '1:393426116947:android:01ebc751b0db2504da01a6',
    messagingSenderId: '393426116947',
    projectId: 'pbl-mad',
    storageBucket: 'pbl-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCykraVGC0-PJoyESC5THcEZyR2SuDa_6U',
    appId: '1:393426116947:ios:b5c2f2126cb8b72cda01a6',
    messagingSenderId: '393426116947',
    projectId: 'pbl-mad',
    storageBucket: 'pbl-mad.firebasestorage.app',
    iosBundleId: 'com.example.quickServePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCykraVGC0-PJoyESC5THcEZyR2SuDa_6U',
    appId: '1:393426116947:ios:b5c2f2126cb8b72cda01a6',
    messagingSenderId: '393426116947',
    projectId: 'pbl-mad',
    storageBucket: 'pbl-mad.firebasestorage.app',
    iosBundleId: 'com.example.quickServePos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoKhh4olbC8chuTHjYRKDk7VCxvMaJw78',
    appId: '1:393426116947:web:d92ff6348df0f8efda01a6',
    messagingSenderId: '393426116947',
    projectId: 'pbl-mad',
    authDomain: 'pbl-mad.firebaseapp.com',
    storageBucket: 'pbl-mad.firebasestorage.app',
    measurementId: 'G-3QLVV1MMZB',
  );
}
